import {supabase} from './supabase.js';
const $=s=>document.querySelector(s),panel=$('#panel');let current='dashboard';let user=null;
const money=v=>'৳'+Number(v||0).toLocaleString('en-BD',{minimumFractionDigits:2});
async function isAdmin(){const {data:{user:u}}=await supabase.auth.getUser();user=u;if(!u)return false;const {data}=await supabase.from('admins').select('user_id,email').eq('user_id',u.id).maybeSingle();return !!data}
function tabs(){document.querySelectorAll('.side button').forEach(b=>b.onclick=()=>{current=b.dataset.tab;document.querySelectorAll('.side button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()})}
async function dashboard(){const [{count:p},{count:o},{count:d},{count:s}]=await Promise.all([supabase.from('products').select('*',{count:'exact',head:true}),supabase.from('orders').select('*',{count:'exact',head:true}),supabase.from('deposit_requests').select('*',{count:'exact',head:true}).eq('status','pending'),supabase.from('service_orders').select('*',{count:'exact',head:true})]);panel.innerHTML=`<h2>📊 Dashboard</h2><div class="stats"><div class="stat">Products<br><b>${p||0}</b></div><div class="stat">Orders<br><b>${o||0}</b></div><div class="stat">Pending deposits<br><b>${d||0}</b></div><div class="stat">Service orders<br><b>${s||0}</b></div></div><br><div class="notice">Admin: <b>${user.email}</b><br>bKash/Nagad: <b>01876872469</b></div>`}
async function products(){const {data}=await supabase.from('products').select('*').order('created_at',{ascending:false});panel.innerHTML=`<h2>🛍️ Products</h2><form id="pf" class="admin-form"><input name="name" required placeholder="Product name"><input name="category" placeholder="Category: Clothing / Services / ..."><input name="price" type="number" step="0.01" required placeholder="Price"><input name="stock" type="number" value="0" placeholder="Stock"><input name="image_url" class="full" placeholder="Image URL"><textarea name="description" class="full" placeholder="Description"></textarea><button class="primary btn3d full">Add Product</button></form><br><div class="table-wrap"><table class="table"><tr><th>Name</th><th>Category</th><th>Price</th><th>Stock</th><th>Active</th><th>Actions</th></tr>${(data||[]).map(p=>`<tr><td><input data-k="name" data-id="${p.id}" value="${esc(p.name)}"></td><td><input data-k="category" data-id="${p.id}" value="${esc(p.category||'')}"></td><td><input data-k="price" data-id="${p.id}" type="number" value="${p.price}"></td><td><input data-k="stock" data-id="${p.id}" type="number" value="${p.stock}"></td><td><input data-k="is_active" data-id="${p.id}" type="checkbox" ${p.is_active?'checked':''}></td><td><div class="row-actions"><button class="secondary saveP" data-id="${p.id}">Save</button><button class="secondary danger delP" data-id="${p.id}">Delete</button></div></td></tr>`).join('')}</table></div>`;$('#pf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await supabase.from('products').insert({name:f.get('name'),category:f.get('category'),price:Number(f.get('price')),stock:Number(f.get('stock')),image_url:f.get('image_url'),description:f.get('description'),is_active:true});if(error)alert(error.message);else render()};document.querySelectorAll('.saveP').forEach(b=>b.onclick=async()=>{const id=b.dataset.id;const val=k=>document.querySelector(`[data-k="${k}"][data-id="${id}"]`);const {error}=await supabase.from('products').update({name:val('name').value,category:val('category').value,price:Number(val('price').value),stock:Number(val('stock').value),is_active:val('is_active').checked,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else alert('Saved')});document.querySelectorAll('.delP').forEach(b=>b.onclick=async()=>{if(!confirm('Delete product?'))return;const {error}=await supabase.from('products').delete().eq('id',b.dataset.id);if(error)alert(error.message);else render()})}
async function services(){const {data}=await supabase.from('service_orders').select('*').order('created_at',{ascending:false});panel.innerHTML=`<h2>🚀 Promotion Service Orders</h2><div class="notice">Orders stay <b>pending</b> until payment is verified. Service processing should start only after confirmation.</div><br><div class="table-wrap"><table class="table"><tr><th>Service</th><th>Target</th><th>Qty</th><th>Price</th><th>Status</th><th>Action</th></tr>${(data||[]).map(o=>`<tr><td>${esc(o.service_type)}</td><td><a href="${esc(o.target_link)}" target="_blank">Open link</a><br><small>${esc(o.notes||'')}</small></td><td>${o.quantity}</td><td>${money(o.price)}</td><td>${o.status}</td><td><select class="svc" data-id="${o.id}"><option ${o.status==='pending'?'selected':''}>pending</option><option ${o.status==='confirmed'?'selected':''}>confirmed</option><option ${o.status==='processing'?'selected':''}>processing</option><option ${o.status==='completed'?'selected':''}>completed</option><option ${o.status==='cancelled'?'selected':''}>cancelled</option></select></td></tr>`).join('')}</table></div>`;document.querySelectorAll('.svc').forEach(s=>s.onchange=async()=>{const {error}=await supabase.from('service_orders').update({status:s.value,updated_at:new Date().toISOString()}).eq('id',s.dataset.id);if(error)alert(error.message)})}
async function packages(){
  const [{data:ps},{data:pkgs}] = await Promise.all([
    supabase.from('products').select('id,name').eq('category','Services').order('name'),
    supabase.from('service_packages').select('*').order('service_type').order('sort_order')
  ]);
  panel.innerHTML=`<h2>💖 Like / Service Packages</h2>
  <div class="notice">Admin can create, edit, activate/deactivate or delete quantity packages. Customer dropdowns update from these packages automatically.</div><br>
  <form id="pkgf" class="admin-form">
    <select name="service_type" required>${(ps||[]).map(p=>`<option>${esc(p.name)}</option>`).join('')}</select>
    <input name="label" required placeholder="Package label e.g. 20,000 Likes">
    <input name="quantity" type="number" min="1" required placeholder="Quantity">
    <input name="price" type="number" min="0" step="0.01" required placeholder="Price (BDT)">
    <input name="sort_order" type="number" value="0" placeholder="Sort order">
    <button class="primary btn3d full">Add Package</button>
  </form><br>
  <div class="table-wrap"><table class="table"><tr><th>Service</th><th>Label</th><th>Qty</th><th>Price</th><th>Active</th><th>Action</th></tr>
  ${(pkgs||[]).map(x=>`<tr>
    <td>${esc(x.service_type)}</td><td><input data-pk="label" data-id="${x.id}" value="${esc(x.label)}"></td>
    <td><input data-pk="quantity" data-id="${x.id}" type="number" value="${x.quantity}"></td>
    <td><input data-pk="price" data-id="${x.id}" type="number" step="0.01" value="${x.price}"></td>
    <td><input data-pk="active" data-id="${x.id}" type="checkbox" ${x.is_active?'checked':''}></td>
    <td><div class="row-actions"><button class="secondary savePk" data-id="${x.id}">Save</button><button class="secondary danger delPk" data-id="${x.id}">Delete</button></div></td>
  </tr>`).join('')}</table></div>`;
  $('#pkgf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await supabase.from('service_packages').insert({service_type:f.get('service_type'),label:f.get('label'),quantity:Number(f.get('quantity')),price:Number(f.get('price')),sort_order:Number(f.get('sort_order')||0),is_active:true});if(error)alert(error.message);else render()};
  document.querySelectorAll('.savePk').forEach(b=>b.onclick=async()=>{const id=b.dataset.id;const g=k=>document.querySelector(`[data-pk="${k}"][data-id="${id}"]`);const {error}=await supabase.from('service_packages').update({label:g('label').value,quantity:Number(g('quantity').value),price:Number(g('price').value),is_active:g('active').checked,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else alert('Package saved')});
  document.querySelectorAll('.delPk').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this package?'))return;const {error}=await supabase.from('service_packages').delete().eq('id',b.dataset.id);if(error)alert(error.message);else render()});
}
async function buttons(){
  const [{data:bs},{data:ps}] = await Promise.all([
    supabase.from('dynamic_buttons').select('*').order('sort_order'),
    supabase.from('products').select('id,name').order('name')
  ]);
  panel.innerHTML=`<h2>🔘 Custom Homepage Buttons</h2>
  <div class="notice">Admin can add new buttons without editing the code. URL buttons open links; Product/Service buttons open the selected item; Section buttons scroll to a page section.</div><br>
  <form id="btnf" class="admin-form">
    <input name="label" required placeholder="Button label">
    <input name="icon" placeholder="Icon e.g. 🚀">
    <select name="action_type"><option value="url">URL</option><option value="product">Product</option><option value="service">Service</option><option value="section">Section</option></select>
    <input name="action_value" class="full" required placeholder="URL / Product ID / Section ID">
    <input name="sort_order" type="number" value="0" placeholder="Sort order">
    <button class="primary btn3d full">Add Button</button>
  </form><br>
  <div class="dynamic-list">${(bs||[]).map(b=>`<div class="dynamic-card"><div><b>${esc(b.icon||'✨')} ${esc(b.label)}</b><div class="mini">${esc(b.action_type)} → ${esc(b.action_value)}</div></div><div class="row-actions" style="margin-top:8px"><button class="secondary toggleBtn" data-id="${b.id}" data-active="${b.is_active}">${b.is_active?'Disable':'Enable'}</button><button class="secondary danger delBtn" data-id="${b.id}">Delete</button></div></div>`).join('')||'<div class="msg">No custom buttons yet.</div>'}</div>`;
  $('#btnf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await supabase.from('dynamic_buttons').insert({label:f.get('label'),icon:f.get('icon'),action_type:f.get('action_type'),action_value:f.get('action_value'),sort_order:Number(f.get('sort_order')||0),is_active:true});if(error)alert(error.message);else render()};
  document.querySelectorAll('.toggleBtn').forEach(b=>b.onclick=async()=>{const {error}=await supabase.from('dynamic_buttons').update({is_active:b.dataset.active!=='true',updated_at:new Date().toISOString()}).eq('id',b.dataset.id);if(error)alert(error.message);else render()});
  document.querySelectorAll('.delBtn').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this button?'))return;const {error}=await supabase.from('dynamic_buttons').delete().eq('id',b.dataset.id);if(error)alert(error.message);else render()});
}
async function categories(){const {data}=await supabase.from('categories').select('*').order('sort_order');panel.innerHTML=`<h2>📂 Categories</h2><form id="cf" class="admin-form"><input name="name" required placeholder="Category name"><input name="slug" required placeholder="slug"><input name="image_url" placeholder="Image URL"><input name="sort_order" type="number" value="0"><textarea name="description" class="full" placeholder="Description"></textarea><button class="primary btn3d full">Add Category</button></form><br>${(data||[]).map(c=>`<div class="wallet-card"><div><b>${esc(c.name)}</b><br><small>${esc(c.slug)} · ${c.is_active?'Active':'Hidden'}</small></div><button class="secondary delC" data-id="${c.id}">Delete</button></div>`).join('')}`;$('#cf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await supabase.from('categories').insert({name:f.get('name'),slug:f.get('slug'),image_url:f.get('image_url'),sort_order:Number(f.get('sort_order')),description:f.get('description'),is_active:true});if(error)alert(error.message);else render()};document.querySelectorAll('.delC').forEach(b=>b.onclick=async()=>{if(!confirm('Delete category?'))return;const {error}=await supabase.from('categories').delete().eq('id',b.dataset.id);if(error)alert(error.message);else render()})}
async function banners(){const {data}=await supabase.from('banners').select('*').order('sort_order');panel.innerHTML=`<h2>🖼️ Banners</h2><form id="bf" class="admin-form"><input name="title" placeholder="Title"><input name="subtitle" placeholder="Subtitle"><input name="image_url" class="full" placeholder="Image URL"><input name="button_text" placeholder="Button text"><input name="button_url" placeholder="Button URL"><button class="primary btn3d full">Add Banner</button></form><br>${(data||[]).map(b=>`<div class="wallet-card"><div><b>${esc(b.title||'Banner')}</b><br><small>${esc(b.subtitle||'')} · ${b.is_active?'Active':'Hidden'}</small></div><button class="secondary delB" data-id="${b.id}">Delete</button></div>`).join('')}`;$('#bf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await supabase.from('banners').insert({title:f.get('title'),subtitle:f.get('subtitle'),image_url:f.get('image_url'),button_text:f.get('button_text'),button_url:f.get('button_url'),is_active:true});if(error)alert(error.message);else render()};document.querySelectorAll('.delB').forEach(b=>b.onclick=async()=>{const {error}=await supabase.from('banners').delete().eq('id',b.dataset.id);if(error)alert(error.message);else render()})}
async function orders(){const {data}=await supabase.from('orders').select('*').order('created_at',{ascending:false});panel.innerHTML=`<h2>📦 Orders</h2><div class="table-wrap"><table class="table"><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Action</th></tr>${(data||[]).map(o=>`<tr><td>${o.id.slice(0,8)}<br><small>${new Date(o.created_at).toLocaleString()}</small></td><td>${esc(o.customer_name||'')}<br>${esc(o.customer_phone||'')}<br>${esc(o.customer_address||'')}</td><td>${money(o.checkout_total||o.total_amount)}</td><td>${o.payment_method||''}<br>${o.payment_status||''}</td><td>${o.status}</td><td><select class="ord" data-id="${o.id}">${['pending','confirmed','processing','shipped','delivered','cancelled'].map(x=>`<option ${o.status===x?'selected':''}>${x}</option>`).join('')}</select></td></tr>`).join('')}</table></div>`;document.querySelectorAll('.ord').forEach(s=>s.onchange=async()=>{const {error}=await supabase.from('orders').update({status:s.value,updated_at:new Date().toISOString()}).eq('id',s.dataset.id);if(error)alert(error.message)})}
async function deposits(){const {data}=await supabase.from('deposit_requests').select('*').order('created_at',{ascending:false}).limit(50);panel.innerHTML=`<h2>💰 Deposit Requests</h2><div class="notice">Merchant bKash/Nagad: <b>01876872469</b></div><br><div class="table-wrap"><table class="table"><tr><th>Amount</th><th>Method</th><th>Sender</th><th>TRX</th><th>Status</th><th>Action</th></tr>${(data||[]).map(d=>`<tr><td>${money(d.amount)}</td><td>${d.payment_method}</td><td>${d.sender_number||''}</td><td>${d.transaction_id||''}</td><td>${d.status}</td><td><div class="row-actions"><button class="secondary dep" data-id="${d.id}" data-act="approve">Approve</button><button class="secondary danger dep" data-id="${d.id}" data-act="reject">Reject</button></div></td></tr>`).join('')}</table></div>`;document.querySelectorAll('.dep').forEach(b=>b.onclick=async()=>{const fn=b.dataset.act==='approve'?'approve_fft_deposit':'reject_fft_deposit';const {error}=await supabase.rpc(fn,{p_deposit_id:b.dataset.id,p_admin_note:'Processed from FFT SHOP Admin'});if(error)alert(error.message);else render()})}
async function settings(){const {data}=await supabase.from('site_settings').select('*').limit(1).maybeSingle();const s=data||{};panel.innerHTML=`<h2>⚙️ Site Settings</h2><form id="sf" class="admin-form"><input name="site_name" value="${esc(s.site_name||'FFT SHOP')}" placeholder="Site name"><input name="logo_url" value="${esc(s.logo_url||'')}" placeholder="Logo URL"><input name="primary_color" value="${esc(s.primary_color||'#7c3aed')}" placeholder="Primary color"><input name="secondary_color" value="${esc(s.secondary_color||'#06b6d4')}" placeholder="Secondary color"><input name="bkash_number" value="${esc(s.bkash_number||'01876872469')}" placeholder="bKash number"><input name="nagad_number" value="${esc(s.nagad_number||'01876872469')}" placeholder="Nagad number"><input name="hero_title" class="full" value="${esc(s.hero_title||'Everything you need, in one place.')}" placeholder="Hero title"><textarea name="hero_subtitle" class="full" placeholder="Hero subtitle">${esc(s.hero_subtitle||'Clothing, premium products and digital services.')}</textarea><input name="hero_image_url" class="full" value="${esc(s.hero_image_url||'')}" placeholder="Hero image URL"><textarea name="announcement" class="full" placeholder="Announcement">${esc(s.announcement||'')}</textarea><button class="primary btn3d full">Save All Settings</button></form>`;$('#sf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);let {data:row}=await supabase.from('site_settings').select('id').limit(1).maybeSingle();const values=Object.fromEntries(f.entries());values.updated_at=new Date().toISOString();const q=row?supabase.from('site_settings').update(values).eq('id',row.id):supabase.from('site_settings').insert(values);const {error}=await q;if(error)alert(error.message);else alert('Settings saved successfully')};}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function render(){if(current==='dashboard')return dashboard();if(current==='products')return products();if(current==='services')return services();if(current==='packages')return packages();if(current==='buttons')return buttons();if(current==='categories')return categories();if(current==='banners')return banners();if(current==='orders')return orders();if(current==='deposits')return deposits();if(current==='settings')return settings()}
async function init(){const ok=await isAdmin();if(!ok){$('#gate').innerHTML='🔒 Access denied. Login with the admin account first: <b>rayhaneditz12@gmail.com</b><br><br><a class="primary btn3d" href="index.html">Go to Login</a>';return}$('#gate').innerHTML='✅ Admin verified: <b>'+user.email+'</b>';$gate=$('#gate');$('#adminUI').classList.remove('hidden');$('#logout').onclick=async()=>{await supabase.auth.signOut();location.href='index.html'};tabs();render()}
let $gate;init();
