import {supabase} from './supabase.js';
const $=s=>document.querySelector(s), gate=$('#adminGate'), panel=$('#adminPanel');
const adminEmail='rayhaneditz12@gmail.com';
let tab='dashboard', products=[], categories=[], banners=[], orders=[], settings={};
const money=v=>'৳'+Number(v||0).toLocaleString('en-BD',{minimumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function init(){
 const {data:{user}}=await supabase.auth.getUser();
 if(!user){gate.innerHTML='<div><b>Login required</b><br>Login with the admin account first.</div><a class="primary" href="index.html">Go to Login</a>';return;}
 if((user.email||'').toLowerCase()!==adminEmail.toLowerCase()){gate.innerHTML='<div><b>Access denied</b><br>This account is not an FFT SHOP administrator.</div><button id="logout" class="primary">Logout</button>';$('#logout').onclick=logout;return;}
 const {data:isAdmin,error}=await supabase.rpc('is_admin');
 if(error||!isAdmin){gate.innerHTML='<div><b>Access denied</b><br>Admin role is not active in Supabase.</div>';return;}
 gate.innerHTML=`<div><b>Admin authenticated</b><br><small>${esc(user.email)}</small></div><button id="logout" class="primary">Logout</button>`;$('#logout').onclick=logout;
 panel.classList.remove('hidden'); await loadAll(); render();
}
async function logout(){await supabase.auth.signOut();location.href='index.html'}
async function loadAll(){
 const [s,c,p,b,o]=await Promise.all([
  supabase.from('site_settings').select('*').limit(1).maybeSingle(),
  supabase.from('categories').select('*').order('sort_order').order('created_at',{ascending:false}),
  supabase.from('products').select('*').order('created_at',{ascending:false}),
  supabase.from('banners').select('*').order('sort_order').order('created_at',{ascending:false}),
  supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(100)
 ]);
 settings=s.data||{}; categories=c.data||[]; products=p.data||[]; banners=b.data||[]; orders=o.data||[];
}
function render(){
 panel.innerHTML=`<div class="admin-tabs">${[['dashboard','📊 Dashboard'],['products','🛍️ Products'],['categories','📂 Categories'],['banners','🖼️ Banners'],['orders','📦 Orders'],['settings','⚙️ Site Settings']].map(x=>`<button class="admin-tab ${tab===x[0]?'active':''}" data-tab="${x[0]}">${x[1]}</button>`).join('')}</div><div id="adminContent"></div>`;
 document.querySelectorAll('.admin-tab').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
 const c=$('#adminContent');
 if(tab==='dashboard') c.innerHTML=dashboard();
 if(tab==='products') c.innerHTML=productsView();
 if(tab==='categories') c.innerHTML=categoriesView();
 if(tab==='banners') c.innerHTML=bannersView();
 if(tab==='orders') c.innerHTML=ordersView();
 if(tab==='settings') c.innerHTML=settingsView();
 bind();
}
function dashboard(){const pending=orders.filter(x=>x.status==='pending').length;const active=products.filter(x=>x.is_active).length;return `<div class="stat-grid"><div class="stat"><span>Products</span><b>${products.length}</b><small>${active} active</small></div><div class="stat"><span>Categories</span><b>${categories.length}</b><small>${categories.filter(x=>x.is_active).length} active</small></div><div class="stat"><span>Orders</span><b>${orders.length}</b><small>${pending} pending</small></div><div class="stat"><span>Sales</span><b>${money(orders.filter(x=>x.status!=='cancelled').reduce((a,x)=>a+Number(x.total_amount||0),0))}</b><small>from loaded orders</small></div></div><div class="admin-card"><h2>Quick Actions</h2><div class="quick-grid"><button class="primary" data-tab="products" data-action="new-product">＋ Add Product</button><button class="secondary" data-tab="categories" data-action="new-category">＋ Add Category</button><button class="secondary" data-tab="banners" data-action="new-banner">＋ Add Banner</button><button class="secondary" data-tab="settings">⚙️ Edit Homepage</button></div></div><div class="admin-card"><h2>Recent Orders</h2>${orders.slice(0,5).map(orderRow).join('')||'<div class="msg">No orders yet.</div>'}</div>`}
function productsView(){return `<div class="section-head admin-head"><h2>Products</h2><button class="primary" data-action="new-product">＋ Add Product</button></div><div class="admin-list">${products.map(p=>`<div class="admin-row"><img src="${esc(p.image_url||'https://placehold.co/100x100?text=FFT')}" alt=""><div class="row-main"><b>${esc(p.name)}</b><small>${money(p.price)} · Stock ${p.stock??0} · ${esc(p.category||'Uncategorized')}</small><span class="badge ${p.is_active?'ok':'off'}">${p.is_active?'Active':'Hidden'}</span></div><div class="row-actions"><button class="secondary edit-product" data-id="${p.id}">Edit</button><button class="danger delete-product" data-id="${p.id}">Delete</button></div></div>`).join('')||'<div class="msg">No products.</div>'}</div>`}
function categoriesView(){return `<div class="section-head admin-head"><h2>Categories</h2><button class="primary" data-action="new-category">＋ Add Category</button></div>${categories.map(x=>`<div class="admin-row"><div class="row-main"><b>${esc(x.name)}</b><small>${esc(x.slug)} · order ${x.sort_order}</small><span class="badge ${x.is_active?'ok':'off'}">${x.is_active?'Active':'Hidden'}</span></div><div class="row-actions"><button class="secondary edit-category" data-id="${x.id}">Edit</button><button class="danger delete-category" data-id="${x.id}">Delete</button></div></div>`).join('')||'<div class="msg">No categories.</div>'}`}
function bannersView(){return `<div class="section-head admin-head"><h2>Banners</h2><button class="primary" data-action="new-banner">＋ Add Banner</button></div>${banners.map(x=>`<div class="admin-row"><img src="${esc(x.image_url||'https://placehold.co/160x90?text=Banner')}" alt=""><div class="row-main"><b>${esc(x.title||'Untitled')}</b><small>${esc(x.subtitle||'')} · order ${x.sort_order}</small><span class="badge ${x.is_active?'ok':'off'}">${x.is_active?'Active':'Hidden'}</span></div><div class="row-actions"><button class="secondary edit-banner" data-id="${x.id}">Edit</button><button class="danger delete-banner" data-id="${x.id}">Delete</button></div></div>`).join('')||'<div class="msg">No banners.</div>'}`}
function orderRow(o){return `<div class="admin-row"><div class="row-main"><b>#${esc(o.id.slice(0,8))} · ${money(o.total_amount)}</b><small>${esc(o.customer_name||'Customer')} · ${esc(o.customer_phone||'')} · ${new Date(o.created_at).toLocaleString()}</small><span class="badge">${esc(o.status||'pending')}</span></div><div class="row-actions"><select class="order-status" data-id="${o.id}">${['pending','confirmed','processing','shipped','delivered','cancelled'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></div></div>`}
function ordersView(){return `<div class="section-head admin-head"><h2>Orders</h2><button class="secondary" data-action="refresh">↻ Refresh</button></div>${orders.map(orderRow).join('')||'<div class="msg">No orders.</div>'}`}
function settingsView(){return `<div class="admin-card"><h2>Homepage / Site Settings</h2><form id="settingsForm" class="form"><input name="site_name" placeholder="Site name" value="${esc(settings.site_name||'FFT SHOP')}"><input name="logo_url" placeholder="Logo URL" value="${esc(settings.logo_url||'')}"><input name="announcement" placeholder="Announcement" value="${esc(settings.announcement||'')}"><input name="hero_title" placeholder="Hero title" value="${esc(settings.hero_title||'')}"><textarea name="hero_subtitle" placeholder="Hero subtitle">${esc(settings.hero_subtitle||'')}</textarea><input name="hero_image_url" placeholder="Hero image URL" value="${esc(settings.hero_image_url||'')}"><div class="two-col"><input name="primary_color" placeholder="#7c3aed" value="${esc(settings.primary_color||'')}"><input name="secondary_color" placeholder="#06b6d4" value="${esc(settings.secondary_color||'')}"></div><button class="primary">Save Site Settings</button></form></div>`}
function modal(title,html){const old=document.querySelector('.admin-modal');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',`<div class="admin-modal"><div class="admin-modal-card"><button class="close" id="modalClose">×</button><h2>${title}</h2>${html}</div></div>`);$('#modalClose').onclick=()=>document.querySelector('.admin-modal').remove()}
function productForm(p={}){modal(p.id?'Edit Product':'Add Product',`<form id="productForm" class="form"><input name="name" required placeholder="Product name" value="${esc(p.name)}"><textarea name="description" placeholder="Description">${esc(p.description)}</textarea><div class="two-col"><input name="price" type="number" step="0.01" required placeholder="Price" value="${p.price??''}"><input name="stock" type="number" required placeholder="Stock" value="${p.stock??0}"></div><input name="category" placeholder="Category name" value="${esc(p.category)}"><input name="image_url" placeholder="Image URL" value="${esc(p.image_url)}"><label><input name="is_active" type="checkbox" ${p.is_active!==false?'checked':''}> Active</label><button class="primary">Save Product</button></form>`);$('#productForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target), data={name:f.get('name'),description:f.get('description'),price:Number(f.get('price')),stock:Number(f.get('stock')),category:f.get('category'),image_url:f.get('image_url'),is_active:f.has('is_active'),updated_at:new Date().toISOString()};const q=p.id?supabase.from('products').update(data).eq('id',p.id):supabase.from('products').insert(data);const {error}=await q;if(error)alert(error.message);else{document.querySelector('.admin-modal').remove();await loadAll();render()}}}
function categoryForm(x={}){modal(x.id?'Edit Category':'Add Category',`<form id="categoryForm" class="form"><input name="name" required placeholder="Name" value="${esc(x.name)}"><input name="slug" required placeholder="slug" value="${esc(x.slug)}"><input name="image_url" placeholder="Image URL" value="${esc(x.image_url)}"><textarea name="description" placeholder="Description">${esc(x.description)}</textarea><input name="sort_order" type="number" value="${x.sort_order??0}"><label><input name="is_active" type="checkbox" ${x.is_active!==false?'checked':''}> Active</label><button class="primary">Save Category</button></form>`);$('#categoryForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),data={name:f.get('name'),slug:f.get('slug'),image_url:f.get('image_url'),description:f.get('description'),sort_order:Number(f.get('sort_order')),is_active:f.has('is_active'),updated_at:new Date().toISOString()};const q=x.id?supabase.from('categories').update(data).eq('id',x.id):supabase.from('categories').insert(data);const {error}=await q;if(error)alert(error.message);else{document.querySelector('.admin-modal').remove();await loadAll();render()}}}
function bannerForm(x={}){modal(x.id?'Edit Banner':'Add Banner',`<form id="bannerForm" class="form"><input name="title" placeholder="Title" value="${esc(x.title)}"><input name="subtitle" placeholder="Subtitle" value="${esc(x.subtitle)}"><input name="image_url" placeholder="Image URL" value="${esc(x.image_url)}"><div class="two-col"><input name="button_text" placeholder="Button text" value="${esc(x.button_text)}"><input name="button_url" placeholder="Button URL" value="${esc(x.button_url)}"></div><input name="sort_order" type="number" value="${x.sort_order??0}"><label><input name="is_active" type="checkbox" ${x.is_active!==false?'checked':''}> Active</label><button class="primary">Save Banner</button></form>`);$('#bannerForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),data={title:f.get('title'),subtitle:f.get('subtitle'),image_url:f.get('image_url'),button_text:f.get('button_text'),button_url:f.get('button_url'),sort_order:Number(f.get('sort_order')),is_active:f.has('is_active'),updated_at:new Date().toISOString()};const q=x.id?supabase.from('banners').update(data).eq('id',x.id):supabase.from('banners').insert(data);const {error}=await q;if(error)alert(error.message);else{document.querySelector('.admin-modal').remove();await loadAll();render()}}}
function bind(){document.querySelectorAll('[data-action="new-product"]').forEach(b=>b.onclick=()=>productForm());document.querySelectorAll('[data-action="new-category"]').forEach(b=>b.onclick=()=>categoryForm());document.querySelectorAll('[data-action="new-banner"]').forEach(b=>b.onclick=()=>bannerForm());document.querySelectorAll('[data-action="refresh"]').forEach(b=>b.onclick=async()=>{await loadAll();render()});document.querySelectorAll('.edit-product').forEach(b=>b.onclick=()=>productForm(products.find(x=>x.id===b.dataset.id)));document.querySelectorAll('.edit-category').forEach(b=>b.onclick=()=>categoryForm(categories.find(x=>x.id===b.dataset.id)));document.querySelectorAll('.edit-banner').forEach(b=>b.onclick=()=>bannerForm(banners.find(x=>x.id===b.dataset.id)));
 document.querySelectorAll('.delete-product').forEach(b=>b.onclick=async()=>{if(confirm('Delete this product?')){const {error}=await supabase.from('products').delete().eq('id',b.dataset.id);if(error)alert(error.message);else{await loadAll();render()}}});document.querySelectorAll('.delete-category').forEach(b=>b.onclick=async()=>{if(confirm('Delete this category?')){const {error}=await supabase.from('categories').delete().eq('id',b.dataset.id);if(error)alert(error.message);else{await loadAll();render()}}});document.querySelectorAll('.delete-banner').forEach(b=>b.onclick=async()=>{if(confirm('Delete this banner?')){const {error}=await supabase.from('banners').delete().eq('id',b.dataset.id);if(error)alert(error.message);else{await loadAll();render()}}});
 document.querySelectorAll('.order-status').forEach(s=>s.onchange=async()=>{const {error}=await supabase.from('orders').update({status:s.value,updated_at:new Date().toISOString()}).eq('id',s.dataset.id);if(error)alert(error.message);else await loadAll()});
 const sf=$('#settingsForm');if(sf)sf.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),data=Object.fromEntries(f.entries());delete data.id;data.updated_at=new Date().toISOString();const {error}=settings.id?await supabase.from('site_settings').update(data).eq('id',settings.id):await supabase.from('site_settings').insert(data);if(error)alert(error.message);else{alert('Site settings saved');await loadAll();render()}};
}
init();
